#修改端口号
server:
  port: 8080
#配置数据库
database:
  url: jdbc:mysql://39.106.188.22:3306/materials?useUnicode=true&characterEncoding=utf-8&useSSL=false
  #url: jdbc:mysql://localhost:3306/materials?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
  username: root
  password: root
spring:
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    type: com.alibaba.druid.pool.DruidDataSource #阿里巴巴数据源
  servlet:
    multipart:
      max-file-size: 10MB # 限制文件上传的大小
      enabled: true  #是否启用文件上传功能
#mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印sql语句
    map-underscore-to-camel-case: true  #下划线转驼峰配置
