server:
  port: 8081

database:
  url: jdbc:mysql://39.107.65.22:3306/materials?useUnicode=true&characterEncoding=utf-8&useSSL=false
  #url: jdbc:mysql://localhost:3306/materials?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
  username: root
  password: root
spring:
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      enabled: true
#mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#jodconverter配置
jodconverter:
  local:
    enabled: true
    max-tasks-per-process: 10
    port-numbers: 8100
    office-home: C:\Program Files (x86)\OpenOffice 4
